version: "3"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - "${WORK_DIRECTORY}:/var/www/html"
      - "./nginx/conf.d:/etc/nginx/conf.d"
    restart: always

  php:
    container_name: php
    build: ./php
    volumes:
      - "${WORK_DIRECTORY}:/var/www/html"
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
