version: "3"

services:
  server:
    build: "./nginx"
    ports:
      - "8008:8080"
    volumes:
      - "./data:/var/www/html"
    restart: always
  app:
    image: php:fpm-alpine
    volumes:
      - "./data:/var/www/html"
    restart: always
  db:
    image: mysql:5
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    restart: always
